### ISSUE TITLE
Write sort function

### ISSUE THREAD

**Issue by nghminh163** [nghminh163/hacktoberfun#22]
Write a program using function which accept 1 array(or vector or list or anything same array) as an argument and return its array sorted small to big.

#### Namefile: sort.* (* is your language)

**Comment by nghminh163** [comment]
> Added Sort function in Shashi/sort.py , You can Merge it ;)

Okay, i'm going to merge your branch to my repo

**Comment by nsvaidya** [comment]
added sort function in nsvaidya/sort.c.
