### ISSUE TITLE
Even or odd ?

### ISSUE THREAD

**Issue by nghminh163** [nghminh163/hacktoberfun#26]
Write 1 program input a integer and return "The number you entered is odd" or "The number you entered is even"

**Comment by charubansal12** [comment]
I can work on this

**Comment by nghminh163** [comment]
@charubansal12 :D It for everyone. Everyone can pull and i will merge theme

**Comment by charubansal12** [comment]
@nghminh163 I am unable to push my code to your repo, i get a 403 error. I have referenced the change I made, can you give me access, or if you could help me with raising  a PR, that would be great.

**Comment by charubansal12** [comment]
Awesome, thanks @nghminh163 !

**Comment by ManavpreetSingh** [comment]
i would like to contribute in c
